#pragma once

#include <GL/glew.h>
#include <GLFW/glfw3.h>

// Keyboard::numbers
#define LYZ_KEY_0					GLFW_KEY_0
#define LYZ_KEY_1					GLFW_KEY_1
#define LYZ_KEY_2					GLFW_KEY_2
#define LYZ_KEY_3					GLFW_KEY_3
#define LYZ_KEY_4					GLFW_KEY_4
#define LYZ_KEY_5					GLFW_KEY_5
#define LYZ_KEY_6					GLFW_KEY_6
#define LYZ_KEY_7					GLFW_KEY_7
#define LYZ_KEY_8					GLFW_KEY_8
#define LYZ_KEY_9					GLFW_KEY_9

// Keyboard::numpad
#define LYZ_KEY_KP_0				GLFW_KEY_KP_0
#define LYZ_KEY_KP_1				GLFW_KEY_KP_1
#define LYZ_KEY_KP_2				GLFW_KEY_KP_2
#define LYZ_KEY_KP_3				GLFW_KEY_KP_3
#define LYZ_KEY_KP_4				GLFW_KEY_KP_4
#define LYZ_KEY_KP_5				GLFW_KEY_KP_5
#define LYZ_KEY_KP_6				GLFW_KEY_KP_6
#define LYZ_KEY_KP_7				GLFW_KEY_KP_7
#define LYZ_KEY_KP_8				GLFW_KEY_KP_8
#define LYZ_KEY_KP_9				GLFW_KEY_KP_9
#define LYZ_KEY_KP_ADD				GLFW_KEY_KP_ADD
#define LYZ_KEY_KP_DECIMAL			GLFW_KEY_KP_DECIMAL
#define LYZ_KEY_KP_DIVIDE			GLFW_KEY_KP_DIVIDE
#define LYZ_KEY_KP_ENTER			GLFW_KEY_KP_ENTER
#define LYZ_KEY_KP_EQUAL			GLFW_KEY_KP_EQUAL
#define LYZ_KEY_KP_MULTIPLY			GLFW_KEY_KP_MULTIPLY
#define LYZ_KEY_KP_SUBTRACT			GLFW_KEY_KP_SUBTRACT

// TO DO: FIGURE THIS OUT!
#define LYZ_KEY_GRAVE_ACCENT		GLFW_KEY_GRAVE_ACCENT
#define LYZ_KEY_KEY_HOME			GLFW_KEY_HOME
#define LYZ_KEY_INSERT				GLFW_KEY_INSERT
#define LYZ_KEY_PERIOD				GLFW_KEY_PERIOD
#define LYZ_KEY_PRINT_SCREEN		GLFW_KEY_PRINT_SCREEN
#define LYZ_KEY_PAGE_UP				GLFW_KEY_PAGE_UP
#define LYZ_KEY_PAGE_DOWN			GLFW_KEY_PAGE_DOWN
#define LYZ_KEY_SCROLL_LOCK			GLFW_KEY_SCROLL_LOCK
#define LYZ_KEY_SEMICOLON			GLFW_KEY_SEMICOLON
#define LYZ_KEY_PAUSE				GLFW_KEY_PAUSE
#define LYZ_KEY_TAB					GLFW_KEY_TAB
#define LYZ_KEY_SPLASH				GLFW_KEY_SLASH
#define LYZ_KEY_UNKNOWN				GLFW_KEY_UNKNOWN
#define LYZ_KEY_WORLD_1				GLFW_KEY_WORLD_1
#define LYZ_KEY_WORLD_2				GLFW_KEY_WORLD_2
#define LYZ_KEY_NUM_LOCK			GLFW_KEY_NUM_LOCK
#define LYZ_KEY_LAST				GLFW_KEY_LAST
#define LYZ_KEY_LEFT_ALT			GLFW_KEY_LEFT_ALT
#define LYZ_KEY_LEFT_BRACKET		GLFW_KEY_LEFT_BRACKET
#define LYZ_KEY_LEFT_CONTROL		GLFW_KEY_LEFT_CONTROL
#define LYZ_KEY_LEFT_SUPER			GLFW_KEY_LEFT_SUPER
#define LYZ_KEY_LEFT_SHIFT			GLFW_KEY_LEFT_SHIFT
#define LYZ_KEY_RIGHT_ALT			GLFW_KEY_RIGHT_ALT
#define LYZ_KEY_RIGHT_BRACKET		GLFW_KEY_RIGHT_BRACKET
#define LYZ_KEY_RIGHT_CONTROL		GLFW_KEY_RIGHT_CONTROL
#define LYZ_KEY_RIGHT_SUPER			GLFW_KEY_RIGHT_SUPER
#define LYZ_KEY_RIGHT_SHIFT			GLFW_KEY_RIGHT_SHIFT
#define LYZ_KEY_SLASH				GLFW_KEY_SLASH
#define LYZ_KEY_SPACE				GLFW_KEY_SPACE

// Keyboard::letters
#define LYZ_KEY_A					GLFW_KEY_A
#define LYZ_KEY_B					GLFW_KEY_B
#define LYZ_KEY_C					GLFW_KEY_C
#define LYZ_KEY_D					GLFW_KEY_D
#define LYZ_KEY_E					GLFW_KEY_E
#define LYZ_KEY_F					GLFW_KEY_F
#define LYZ_KEY_G					GLFW_KEY_G
#define LYZ_KEY_H					GLFW_KEY_H
#define LYZ_KEY_I					GLFW_KEY_I
#define LYZ_KEY_J					GLFW_KEY_J
#define LYZ_KEY_K					GLFW_KEY_K
#define LYZ_KEY_L					GLFW_KEY_L
#define LYZ_KEY_M					GLFW_KEY_M
#define LYZ_KEY_N					GLFW_KEY_N
#define LYZ_KEY_O					GLFW_KEY_O
#define LYZ_KEY_P					GLFW_KEY_P
#define LYZ_KEY_Q					GLFW_KEY_Q
#define LYZ_KEY_R					GLFW_KEY_R
#define LYZ_KEY_S					GLFW_KEY_S
#define LYZ_KEY_T					GLFW_KEY_T
#define LYZ_KEY_U					GLFW_KEY_U
#define LYZ_KEY_V					GLFW_KEY_V
#define LYZ_KEY_W					GLFW_KEY_W
#define LYZ_KEY_X					GLFW_KEY_X
#define LYZ_KEY_Y					GLFW_KEY_Y
#define LYZ_KEY_Z					GLFW_KEY_Z

// Keyboard::specials_2
#define LYZ_KEY_APOSTROPHE			GLFW_KEY_APOSTROPHE
#define LYZ_KEY_BACKSLASH			GLFW_KEY_BACKSLASH
#define LYZ_KEY_BACKSPACE			GLFW_KEY_BACKSPACE
#define LYZ_KEY_CAPS_LOCK			GLFW_KEY_CAPS_LOCK
#define LYZ_KEY_COMMA				GLFW_KEY_COMMA
#define LYZ_KEY_DELETE				GLFW_KEY_DELETE
#define LYZ_KEY_END					GLFW_KEY_END
#define LYZ_KEY_ENTER				GLFW_KEY_ENTER
#define LYZ_KEY_EQUAL				GLFW_KEY_EQUAL
#define LYZ_KEY_ESCAPE				GLFW_KEY_ESCAPE

// Keyboard::functions
#define LYZ_KEY_F1					GLFW_KEY_F1
#define LYZ_KEY_F2					GLFW_KEY_F2
#define LYZ_KEY_F3					GLFW_KEY_F3
#define LYZ_KEY_F4					GLFW_KEY_F4
#define LYZ_KEY_F5					GLFW_KEY_F5
#define LYZ_KEY_F6					GLFW_KEY_F6
#define LYZ_KEY_F7					GLFW_KEY_F7
#define LYZ_KEY_F8					GLFW_KEY_F8
#define LYZ_KEY_F9					GLFW_KEY_F9
#define LYZ_KEY_F10					GLFW_KEY_F10
#define LYZ_KEY_F11					GLFW_KEY_F11
#define LYZ_KEY_F12					GLFW_KEY_F12

// Keyboard::arrows
#define LYZ_KEY_DOWN				GLFW_KEY_DOWN
#define LYZ_KEY_UP					GLFW_KEY_UP
#define LYZ_KEY_LEFT				GLFW_KEY_LEFT
#define LYZ_KEY_RIGHT				GLFW_KEY_RIGHT

// Mouse::buttons
#define LYZ_MOUSE_BUTTON_1			GLFW_MOUSE_BUTTON_1
#define LYZ_MOUSE_BUTTON_2			GLFW_MOUSE_BUTTON_2
#define LYZ_MOUSE_BUTTON_3			GLFW_MOUSE_BUTTON_3
#define LYZ_MOUSE_BUTTON_4			GLFW_MOUSE_BUTTON_4
#define LYZ_MOUSE_BUTTON_5			GLFW_MOUSE_BUTTON_5
#define LYZ_MOUSE_BUTTON_6			GLFW_MOUSE_BUTTON_6
#define LYZ_MOUSE_BUTTON_7			GLFW_MOUSE_BUTTON_7
#define LYZ_MOUSE_BUTTON_8			GLFW_MOUSE_BUTTON_8
#define LYZ_MOUSE_BUTTON_LAST		GLFW_MOUSE_BUTTON_LAST
#define LYZ_STICKY_MOUSE_BUTTON		GLFW_STICKY_MOUSE_BUTTONS
#define LYZ_MOUSE_BUTTON_LEFT		GLFW_MOUSE_BUTTON_LEFT
#define LYZ_MOUSE_BUTTON_MIDDLE		GLFW_MOUSE_BUTTON_MIDDLE
#define LYZ_MOUSE_BUTTON_RIGHT		GLFW_MOUSE_BUTTON_RIGHT
